#+title: shin-geta-karabiner-elements
#+author: conao3

* shin-geta-karabiner-elements

[[https://github.com/conao3/shin-geta-karabiner-elements][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/shin-geta-karabiner-elements.png]]

[[https://github.com/conao3/shin-geta-karabiner-elements/blob/master/LICENSE][https://img.shields.io/github/license/conao3/shin-geta-karabiner-elements.svg?style=flat-square]]
[[https://github.com/conao3/shin-geta-karabiner-elements/releases][https://img.shields.io/github/tag/conao3/shin-geta-karabiner-elements.svg?style=flat-square]]

A configuration file for [[https://pqrs.org/osx/karabiner/][Karabiner-Elements]] that enables the Shin-Geta (新下駄配列) Japanese keyboard layout on macOS.

** Overview

Shin-Geta is a Japanese keyboard layout designed for efficient kana input. This repository provides ready-to-use configuration files for Karabiner-Elements, making it easy to use Shin-Geta on your Mac.

** Requirements

- macOS
- [[https://pqrs.org/osx/karabiner/][Karabiner-Elements]]

** Installation

1. Install Karabiner-Elements from the official website
2. Download the configuration file from this repository
3. Place it in your Karabiner-Elements complex modifications folder

** Usage

After installation, enable the Shin-Geta rules from the Karabiner-Elements preferences under Complex Modifications.

** Contributing

Contributions are welcome. Feel free to open issues for bug reports or feature requests, and pull requests are appreciated.

** License

#+begin_example
  Affero General Public License Version 3 (AGPLv3)
  Copyright (c) Naoya Yamashita - https://conao3.com
  https://github.com/conao3/shin-geta-karabiner-elements/blob/master/LICENSE
#+end_example

** Author

- Naoya Yamashita ([[https://github.com/conao3][conao3]])
